#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <dxgi1_2.h>
#include <wrl/client.h>

#include <chrono>
#include <memory>
#include <cstring>

#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "d3dcompiler.lib")
#pragma comment(lib, "dxgi.lib")

using Microsoft::WRL::ComPtr;

extern "C" {
struct SGVideoFrame { UINT32 width, height, stride, reserved; UINT64 acquireMicroseconds, gpuCopyMicroseconds, mapReadbackMicroseconds; };
struct SGVideoRendererStats { UINT64 renderAttempts, successfulPresents, failedPresents, deviceResets, lastPresentMicroseconds; UINT32 viewportX, viewportY, viewportWidth, viewportHeight; };
__declspec(dllexport) HRESULT WINAPI SGVideo_Create(void** handle);
__declspec(dllexport) void WINAPI SGVideo_Destroy(void* handle);
__declspec(dllexport) HRESULT WINAPI SGVideo_StartCapture(void* handle);
__declspec(dllexport) HRESULT WINAPI SGVideo_GetDimensions(void* handle, UINT32* width, UINT32* height);
__declspec(dllexport) HRESULT WINAPI SGVideo_AcquireFrame(void* handle, BYTE* destination, UINT32 destinationBytes, UINT32 timeoutMilliseconds, SGVideoFrame* frame);
__declspec(dllexport) HRESULT WINAPI SGVideo_GetLastError(void* handle);
__declspec(dllexport) HRESULT WINAPI SGVideo_CreateRenderer(HWND hwnd, void** handle);
__declspec(dllexport) void WINAPI SGVideo_DestroyRenderer(void* handle);
__declspec(dllexport) HRESULT WINAPI SGVideo_RenderBGRA(void* handle, const BYTE* pixels, UINT32 width, UINT32 height, UINT32 stride);
__declspec(dllexport) HRESULT WINAPI SGVideo_ResizeRenderer(void* handle, UINT32 width, UINT32 height);
__declspec(dllexport) HRESULT WINAPI SGVideo_RedrawRenderer(void* handle);
__declspec(dllexport) HRESULT WINAPI SGVideo_GetRendererStats(void* handle, SGVideoRendererStats* stats);
__declspec(dllexport) HRESULT WINAPI SGVideo_GetRendererLastError(void* handle);
}

namespace {
static UINT64 ElapsedMicroseconds(std::chrono::steady_clock::time_point started) { return static_cast<UINT64>(std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now() - started).count()); }

class VideoCapture final {
public:
 HRESULT Start(); HRESULT Dimensions(UINT32* width, UINT32* height) const; HRESULT Acquire(BYTE*, UINT32, UINT32, SGVideoFrame*); HRESULT LastError() const { return lastError_; }
private:
 HRESULT SetError(HRESULT hr) { lastError_ = hr; return hr; } HRESULT EnsureStaging(UINT32, UINT32, DXGI_FORMAT); void ReleaseResources();
 ComPtr<IDXGIFactory1> factory_; ComPtr<ID3D11Device> device_; ComPtr<ID3D11DeviceContext> context_; ComPtr<IDXGIOutput1> output_; ComPtr<IDXGIOutputDuplication> duplication_; ComPtr<ID3D11Texture2D> staging_; D3D_FEATURE_LEVEL featureLevel_{}; DXGI_FORMAT format_ = DXGI_FORMAT_UNKNOWN; UINT32 width_ = 0, height_ = 0; HRESULT lastError_ = S_OK;
};
HRESULT VideoCapture::Start() { ReleaseResources(); HRESULT hr=CreateDXGIFactory1(IID_PPV_ARGS(&factory_)); if(FAILED(hr)) return SetError(hr); ComPtr<IDXGIAdapter1> a; ComPtr<IDXGIOutput> o; bool origin=false; for(UINT i=0;;++i){ ComPtr<IDXGIAdapter1> x; hr=factory_->EnumAdapters1(i,&x); if(hr==DXGI_ERROR_NOT_FOUND)break; if(FAILED(hr))continue; for(UINT j=0;;++j){ComPtr<IDXGIOutput> y; hr=x->EnumOutputs(j,&y); if(hr==DXGI_ERROR_NOT_FOUND)break; DXGI_OUTPUT_DESC d{}; if(FAILED(hr)||FAILED(y->GetDesc(&d))||!d.AttachedToDesktop)continue; bool contains=d.DesktopCoordinates.left<=0&&d.DesktopCoordinates.top<=0&&d.DesktopCoordinates.right>0&&d.DesktopCoordinates.bottom>0; if(!o||(contains&&!origin)){a=x;o=y;origin=contains;}}} if(!a||!o)return SetError(DXGI_ERROR_NOT_FOUND); static constexpr D3D_FEATURE_LEVEL levels[]={D3D_FEATURE_LEVEL_11_1,D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_1,D3D_FEATURE_LEVEL_10_0}; hr=D3D11CreateDevice(a.Get(),D3D_DRIVER_TYPE_UNKNOWN,nullptr,D3D11_CREATE_DEVICE_BGRA_SUPPORT,levels,ARRAYSIZE(levels),D3D11_SDK_VERSION,&device_,&featureLevel_,&context_); if(FAILED(hr))return SetError(hr); hr=o.As(&output_); if(FAILED(hr))return SetError(hr); hr=output_->DuplicateOutput(device_.Get(),&duplication_); if(FAILED(hr))return SetError(hr); DXGI_OUTDUPL_DESC d{}; duplication_->GetDesc(&d); return EnsureStaging(d.ModeDesc.Width,d.ModeDesc.Height,d.ModeDesc.Format); }
HRESULT VideoCapture::Dimensions(UINT32* w,UINT32* h)const {if(!w||!h)return E_POINTER;*w=width_;*h=height_;return width_&&height_?S_OK:DXGI_ERROR_INVALID_CALL;}
HRESULT VideoCapture::Acquire(BYTE* dst,UINT32 bytes,UINT32 timeout,SGVideoFrame* f){if(!dst||!f)return SetError(E_POINTER);if(!duplication_||!context_||!staging_)return SetError(DXGI_ERROR_INVALID_CALL);if(static_cast<UINT64>(width_)*height_*4>bytes)return SetError(HRESULT_FROM_WIN32(ERROR_INSUFFICIENT_BUFFER));*f={};auto started=std::chrono::steady_clock::now();DXGI_OUTDUPL_FRAME_INFO fi{};ComPtr<IDXGIResource>r;HRESULT hr=duplication_->AcquireNextFrame(timeout,&fi,&r);f->acquireMicroseconds=ElapsedMicroseconds(started);if(hr==DXGI_ERROR_WAIT_TIMEOUT)return hr;if(hr==DXGI_ERROR_ACCESS_LOST){Start();return SetError(hr);}if(FAILED(hr))return SetError(hr);struct R{IDXGIOutputDuplication*d;~R(){d->ReleaseFrame();}}release{duplication_.Get()};ComPtr<ID3D11Texture2D> t;hr=r.As(&t);if(FAILED(hr))return SetError(hr);D3D11_TEXTURE2D_DESC d{};t->GetDesc(&d);if(d.Width!=width_||d.Height!=height_||d.Format!=format_){hr=EnsureStaging(d.Width,d.Height,d.Format);if(FAILED(hr))return hr;}auto copy=std::chrono::steady_clock::now();context_->CopyResource(staging_.Get(),t.Get());f->gpuCopyMicroseconds=ElapsedMicroseconds(copy);auto map=std::chrono::steady_clock::now();D3D11_MAPPED_SUBRESOURCE m{};hr=context_->Map(staging_.Get(),0,D3D11_MAP_READ,0,&m);if(FAILED(hr))return SetError(hr);struct U{ID3D11DeviceContext*c;ID3D11Resource*r;~U(){c->Unmap(r,0);}}unmap{context_.Get(),staging_.Get()};if(!m.pData||m.RowPitch<width_*4)return SetError(E_FAIL);for(UINT32 y=0;y<height_;++y)memcpy(dst+static_cast<size_t>(y)*width_*4,static_cast<const BYTE*>(m.pData)+static_cast<size_t>(y)*m.RowPitch,static_cast<size_t>(width_)*4);f->mapReadbackMicroseconds=ElapsedMicroseconds(map);f->width=width_;f->height=height_;f->stride=width_*4;return SetError(S_OK);}
HRESULT VideoCapture::EnsureStaging(UINT32 w,UINT32 h,DXGI_FORMAT fmt){if(!w||!h||fmt!=DXGI_FORMAT_B8G8R8A8_UNORM)return SetError(DXGI_ERROR_UNSUPPORTED);if(staging_&&w==width_&&h==height_&&fmt==format_)return SetError(S_OK);staging_.Reset();D3D11_TEXTURE2D_DESC d{};d.Width=w;d.Height=h;d.MipLevels=d.ArraySize=1;d.Format=fmt;d.SampleDesc.Count=1;d.Usage=D3D11_USAGE_STAGING;d.CPUAccessFlags=D3D11_CPU_ACCESS_READ;HRESULT hr=device_->CreateTexture2D(&d,nullptr,&staging_);if(SUCCEEDED(hr)){width_=w;height_=h;format_=fmt;}return SetError(hr);}
void VideoCapture::ReleaseResources(){staging_.Reset();duplication_.Reset();output_.Reset();context_.Reset();device_.Reset();factory_.Reset();width_=height_=0;format_=DXGI_FORMAT_UNKNOWN;}

class VideoRenderer final {
public:
 HRESULT Create(HWND hwnd) { hwnd_=hwnd; return Initialize(); }
 HRESULT Render(const BYTE* pixels, UINT32 width, UINT32 height, UINT32 stride) { if(!pixels||!width||!height||stride<width*4)return SetError(E_INVALIDARG); HRESULT hr=EnsureReady(); if(FAILED(hr))return hr; if(width!=frameWidth_||height!=frameHeight_){ srv_.Reset(); texture_.Reset(); D3D11_TEXTURE2D_DESC d{};d.Width=width;d.Height=height;d.MipLevels=d.ArraySize=1;d.Format=DXGI_FORMAT_B8G8R8A8_UNORM;d.SampleDesc.Count=1;d.Usage=D3D11_USAGE_DYNAMIC;d.BindFlags=D3D11_BIND_SHADER_RESOURCE;d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;hr=device_->CreateTexture2D(&d,nullptr,&texture_);if(FAILED(hr))return SetError(hr);hr=device_->CreateShaderResourceView(texture_.Get(),nullptr,&srv_);if(FAILED(hr))return SetError(hr);frameWidth_=width;frameHeight_=height;} D3D11_MAPPED_SUBRESOURCE m{};hr=context_->Map(texture_.Get(),0,D3D11_MAP_WRITE_DISCARD,0,&m);if(FAILED(hr))return SetError(hr);for(UINT32 y=0;y<height;++y)memcpy(static_cast<BYTE*>(m.pData)+static_cast<size_t>(y)*m.RowPitch,pixels+static_cast<size_t>(y)*stride,static_cast<size_t>(width)*4);context_->Unmap(texture_.Get(),0);return Draw(); }
 HRESULT Resize(UINT32 w,UINT32 h) { if(!w||!h)return S_OK; clientWidth_=w;clientHeight_=h;if(!swapChain_)return S_OK; rtv_.Reset();HRESULT hr=swapChain_->ResizeBuffers(0,w,h,DXGI_FORMAT_UNKNOWN,0);if(FAILED(hr))return Recover(hr);return CreateRenderTarget(); }
 HRESULT Redraw(){return texture_?Draw():S_OK;} HRESULT LastError()const{return lastError_;} HRESULT Stats(SGVideoRendererStats* s)const{if(!s)return E_POINTER;*s=stats_;return S_OK;}
private:
 HRESULT SetError(HRESULT hr){lastError_=hr;return hr;} HRESULT EnsureReady(){if(device_&&swapChain_&&rtv_)return S_OK;return Initialize();}
 HRESULT Initialize(){Release(); if(!hwnd_||!IsWindow(hwnd_))return SetError(E_INVALIDARG); RECT r{};GetClientRect(hwnd_,&r);clientWidth_=r.right-r.left;clientHeight_=r.bottom-r.top; if(!clientWidth_||!clientHeight_)return SetError(S_OK);UINT flags=D3D11_CREATE_DEVICE_BGRA_SUPPORT;static constexpr D3D_FEATURE_LEVEL levels[]={D3D_FEATURE_LEVEL_11_1,D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_1};HRESULT hr=D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,flags,levels,ARRAYSIZE(levels),D3D11_SDK_VERSION,&device_,nullptr,&context_);if(FAILED(hr))hr=D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,flags,levels,ARRAYSIZE(levels),D3D11_SDK_VERSION,&device_,nullptr,&context_);if(FAILED(hr))return SetError(hr);ComPtr<IDXGIDevice> dxgi;device_.As(&dxgi);ComPtr<IDXGIAdapter> adapter;dxgi->GetAdapter(&adapter);ComPtr<IDXGIFactory> factory;adapter->GetParent(IID_PPV_ARGS(&factory));DXGI_SWAP_CHAIN_DESC d{};d.BufferDesc.Width=clientWidth_;d.BufferDesc.Height=clientHeight_;d.BufferDesc.Format=DXGI_FORMAT_B8G8R8A8_UNORM;d.SampleDesc.Count=1;d.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;d.BufferCount=2;d.OutputWindow=hwnd_;d.Windowed=TRUE;d.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;hr=factory->CreateSwapChain(device_.Get(),&d,&swapChain_);if(FAILED(hr))return SetError(hr);hr=CreateRenderTarget();if(FAILED(hr))return hr;static const char* vs="struct V{float4 p:POSITION;float2 t:TEXCOORD;};V main(uint id:SV_VertexID){float2 p[3]={float2(-1,-1),float2(-1,3),float2(3,-1)};float2 t[3]={float2(0,1),float2(0,-1),float2(2,1)};V o;o.p=float4(p[id],0,1);o.t=t[id];return o;}";static const char* ps="Texture2D x:register(t0);SamplerState s:register(s0);float4 main(float4 p:SV_POSITION,float2 t:TEXCOORD):SV_TARGET{return x.Sample(s,t);}";ComPtr<ID3DBlob>a,b,e;hr=D3DCompile(vs,strlen(vs),nullptr,nullptr,nullptr,"main","vs_4_0",0,0,&a,&e);if(FAILED(hr))return SetError(hr);hr=D3DCompile(ps,strlen(ps),nullptr,nullptr,nullptr,"main","ps_4_0",0,0,&b,&e);if(FAILED(hr))return SetError(hr);device_->CreateVertexShader(a->GetBufferPointer(),a->GetBufferSize(),nullptr,&vs_);device_->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&ps_);D3D11_SAMPLER_DESC sd{};sd.Filter=D3D11_FILTER_MIN_MAG_MIP_LINEAR;sd.AddressU=sd.AddressV=sd.AddressW=D3D11_TEXTURE_ADDRESS_CLAMP;device_->CreateSamplerState(&sd,&sampler_);return SetError(S_OK);}
 HRESULT CreateRenderTarget(){ComPtr<ID3D11Texture2D>b;HRESULT hr=swapChain_->GetBuffer(0,IID_PPV_ARGS(&b));if(FAILED(hr))return SetError(hr);return SetError(device_->CreateRenderTargetView(b.Get(),nullptr,&rtv_));}
 HRESULT Draw(){auto started=std::chrono::steady_clock::now();RECT r{};GetClientRect(hwnd_,&r);UINT w=r.right-r.left,h=r.bottom-r.top;if(!w||!h)return S_OK;if(w!=clientWidth_||h!=clientHeight_){HRESULT hr=Resize(w,h);if(FAILED(hr))return hr;}float black[]={0,0,0,1};context_->OMSetRenderTargets(1,rtv_.GetAddressOf(),nullptr);context_->ClearRenderTargetView(rtv_.Get(),black);UINT vw=w,vh=static_cast<UINT>(static_cast<UINT64>(w)*frameHeight_/frameWidth_);if(vh>h){vh=h;vw=static_cast<UINT>(static_cast<UINT64>(h)*frameWidth_/frameHeight_);}D3D11_VIEWPORT vp{static_cast<float>((w-vw)/2),static_cast<float>((h-vh)/2),static_cast<float>(vw),static_cast<float>(vh),0,1};context_->RSSetViewports(1,&vp);context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);context_->VSSetShader(vs_.Get(),nullptr,0);context_->PSSetShader(ps_.Get(),nullptr,0);context_->PSSetShaderResources(0,1,srv_.GetAddressOf());context_->PSSetSamplers(0,1,sampler_.GetAddressOf());context_->Draw(3,0);HRESULT hr=swapChain_->Present(0,0);stats_.renderAttempts++;stats_.lastPresentMicroseconds=ElapsedMicroseconds(started);stats_.viewportX=(w-vw)/2;stats_.viewportY=(h-vh)/2;stats_.viewportWidth=vw;stats_.viewportHeight=vh;if(SUCCEEDED(hr)){stats_.successfulPresents++;return SetError(S_OK);}stats_.failedPresents++;if(hr==DXGI_ERROR_DEVICE_REMOVED||hr==DXGI_ERROR_DEVICE_RESET){stats_.deviceResets++;Initialize();}return SetError(hr);}
 HRESULT Recover(HRESULT hr){if(hr==DXGI_ERROR_DEVICE_REMOVED||hr==DXGI_ERROR_DEVICE_RESET){stats_.deviceResets++;return Initialize();}return SetError(hr);} void Release(){srv_.Reset();texture_.Reset();sampler_.Reset();ps_.Reset();vs_.Reset();rtv_.Reset();swapChain_.Reset();context_.Reset();device_.Reset();frameWidth_=frameHeight_=0;}
 HWND hwnd_{};UINT32 clientWidth_{},clientHeight_{},frameWidth_{},frameHeight_{};ComPtr<ID3D11Device>device_;ComPtr<ID3D11DeviceContext>context_;ComPtr<IDXGISwapChain>swapChain_;ComPtr<ID3D11RenderTargetView>rtv_;ComPtr<ID3D11Texture2D>texture_;ComPtr<ID3D11ShaderResourceView>srv_;ComPtr<ID3D11VertexShader>vs_;ComPtr<ID3D11PixelShader>ps_;ComPtr<ID3D11SamplerState>sampler_;SGVideoRendererStats stats_{};HRESULT lastError_=S_OK;
};
}
HRESULT WINAPI SGVideo_Create(void** h){if(!h)return E_POINTER;*h=new(std::nothrow)VideoCapture();return*h?S_OK:E_OUTOFMEMORY;} void WINAPI SGVideo_Destroy(void*h){delete static_cast<VideoCapture*>(h);} HRESULT WINAPI SGVideo_StartCapture(void*h){return h?static_cast<VideoCapture*>(h)->Start():E_POINTER;} HRESULT WINAPI SGVideo_GetDimensions(void*h,UINT32*w,UINT32*he){return h?static_cast<VideoCapture*>(h)->Dimensions(w,he):E_POINTER;} HRESULT WINAPI SGVideo_AcquireFrame(void*h,BYTE*d,UINT32 b,UINT32 t,SGVideoFrame*f){return h?static_cast<VideoCapture*>(h)->Acquire(d,b,t,f):E_POINTER;} HRESULT WINAPI SGVideo_GetLastError(void*h){return h?static_cast<VideoCapture*>(h)->LastError():E_POINTER;}
HRESULT WINAPI SGVideo_CreateRenderer(HWND hwnd,void**h){if(!h)return E_POINTER;auto*r=new(std::nothrow)VideoRenderer();if(!r)return E_OUTOFMEMORY;HRESULT hr=r->Create(hwnd);if(FAILED(hr)){delete r;return hr;}*h=r;return S_OK;}void WINAPI SGVideo_DestroyRenderer(void*h){delete static_cast<VideoRenderer*>(h);}HRESULT WINAPI SGVideo_RenderBGRA(void*h,const BYTE*p,UINT32 w,UINT32 he,UINT32 s){return h?static_cast<VideoRenderer*>(h)->Render(p,w,he,s):E_POINTER;}HRESULT WINAPI SGVideo_ResizeRenderer(void*h,UINT32 w,UINT32 he){return h?static_cast<VideoRenderer*>(h)->Resize(w,he):E_POINTER;}HRESULT WINAPI SGVideo_RedrawRenderer(void*h){return h?static_cast<VideoRenderer*>(h)->Redraw():E_POINTER;}HRESULT WINAPI SGVideo_GetRendererStats(void*h,SGVideoRendererStats*s){return h?static_cast<VideoRenderer*>(h)->Stats(s):E_POINTER;}HRESULT WINAPI SGVideo_GetRendererLastError(void*h){return h?static_cast<VideoRenderer*>(h)->LastError():E_POINTER;}
