"use client";

import { useEffect, useState } from "react";
import { ExternalLink } from "lucide-react";
import { RemoteFeatureGate } from "@/components/dashboard/devices/remote-feature-gate";
import type { RemoteFeatureAccess } from "@/lib/remote-feature-access";
import { remoteErrorMessage } from "@/lib/remote-feature-errors";

type Session = { sessionId: string; expiresAt: string; status: string };
type Props = { deviceId: string; available: boolean; access: RemoteFeatureAccess };
function errorMessage(error: unknown, fallback: string) { return remoteErrorMessage(error instanceof Error ? error.message : error, fallback); }
export default function DeviceRDP({ deviceId, available, access }: Props) {
 const [session,setSession]=useState<Session|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[missing,setMissing]=useState(false);
 const sessionId=session?.sessionId;
 useEffect(()=>{if(!access.canUse)return;const controller=new AbortController();void(async()=>{try{const response=await fetch(`/api/devices/${deviceId}/rdp`,{cache:"no-store",signal:controller.signal});if(response.status===204)return;const body=await response.json();if(!response.ok)throw new Error(body.error||"SESSION_LOOKUP_FAILED");setSession(body)}catch(error){if(!controller.signal.aborted)setMessage(errorMessage(error,"Remote Desktop session status is unavailable."))}})();return()=>controller.abort()},[deviceId,access.canUse]);
 useEffect(()=>{if(!access.canUse||!sessionId)return;const controller=new AbortController();const timer=setInterval(async()=>{try{const response=await fetch(`/api/devices/${deviceId}/rdp/${sessionId}`,{cache:"no-store",signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error||"SESSION_LOOKUP_FAILED");if(["closed","failed"].includes(body.status)||Date.parse(body.expiresAt)<=Date.now())setSession(null);else setSession(body)}catch(error){if(!controller.signal.aborted)setMessage(errorMessage(error,"Remote Desktop session status is unavailable."))}},5000);return()=>{controller.abort();clearInterval(timer)}},[deviceId,sessionId,access.canUse]);
 async function start(){setBusy(true);setMessage("");setMissing(false);try{const response=await fetch(`/api/devices/${deviceId}/rdp`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const body=await response.json();if(!response.ok)throw new Error(body.error||"SESSION_CREATE_FAILED");setSession({sessionId:body.sessionId,expiresAt:body.expiresAt,status:"requested"});let opened=false;const markOpened=()=>{opened=true;window.removeEventListener("blur",markOpened);document.removeEventListener("visibilitychange",onVisibility)};const onVisibility=()=>{if(document.visibilityState==="hidden")markOpened()};window.addEventListener("blur",markOpened,{once:true});document.addEventListener("visibilitychange",onVisibility);window.location.href=body.launchUrl;setTimeout(()=>{window.removeEventListener("blur",markOpened);document.removeEventListener("visibilitychange",onVisibility);if(!opened)setMissing(true)},2000)}catch(error){setMessage(errorMessage(error,"Remote Desktop request failed."))}finally{setBusy(false)}}
 async function close(){if(!session)return;setBusy(true);try{const response=await fetch(`/api/devices/${deviceId}/rdp/${session.sessionId}`,{method:"DELETE"});if(!response.ok){const body=await response.json();throw new Error(body.error||"SESSION_CLOSE_FAILED")}setSession(null)}catch(error){setMessage(errorMessage(error,"Remote Desktop session could not be closed."))}finally{setBusy(false)}}
 if(!access.canUse)return <RemoteFeatureGate access={access} feature="Remote Desktop"><button type="button" className="sg-button sg-button-secondary"><ExternalLink size={16}/>Remote Desktop</button></RemoteFeatureGate>;
 return <div>{<button type="button" disabled={busy||(!session&&!available)} onClick={()=>void(session?close():start())} className="sg-button sg-button-secondary"><ExternalLink size={16}/>{busy?"Opening...":session?"Close Remote Desktop":"Remote Desktop"}</button>}{message&&<p role="status" className="sr-only">{message}</p>}{missing&&<div role="dialog" aria-modal="true" aria-label="SentinelGrid Remote required" className="mt-3 rounded border border-zinc-700 bg-zinc-900 p-4 text-sm text-zinc-100"><p className="font-medium">SentinelGrid Remote</p><p className="mt-1 text-zinc-300">SentinelGrid Remote is required to start this session.</p><div className="mt-3 flex gap-2"><a className="sg-button sg-button-secondary" href={`/api/remote/rdp/download?deviceId=${encodeURIComponent(deviceId)}&sessionId=${encodeURIComponent(session?.sessionId??"")}`}>Download SentinelGrid Remote</a><button type="button" className="sg-button sg-button-secondary" onClick={()=>void(start())}>Try Again</button></div></div>}</div>;
}
