"use client";

import { useEffect, useState } from "react";
import { Download, ExternalLink, Monitor, RotateCcw, Wrench, X } from "lucide-react";
import ViewportDialog from "@/components/dashboard/viewport-dialog";
import { RemoteFeatureGate } from "@/components/dashboard/devices/remote-feature-gate";
import type { RemoteFeatureAccess } from "@/lib/remote-feature-access";
import { remoteErrorMessage } from "@/lib/remote-feature-errors";

type Session = { sessionId: string; expiresAt: string; status: string };
type Props = { deviceId: string; available: boolean; access: RemoteFeatureAccess };
function errorMessage(error: unknown, fallback: string) { return remoteErrorMessage(error instanceof Error ? error.message : error, fallback); }
export default function DeviceRDP({ deviceId, available, access }: Props) {
 const [session,setSession]=useState<Session|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[missing,setMissing]=useState(false);
 const sessionId=session?.sessionId;
 useEffect(()=>{if(!access.canUse)return;const controller=new AbortController();void(async()=>{try{const response=await fetch(`/api/devices/${deviceId}/rdp`,{cache:"no-store",signal:controller.signal});if(response.status===204)return;const body=await response.json();if(!response.ok)throw new Error(body.error||"SESSION_LOOKUP_FAILED");setSession(body)}catch(error){if(!controller.signal.aborted)setMessage(errorMessage(error,"Remote Desktop session status is unavailable."))}})();return()=>controller.abort()},[deviceId,access.canUse]);
 useEffect(()=>{if(!access.canUse||!sessionId)return;const controller=new AbortController();const timer=setInterval(async()=>{try{const response=await fetch(`/api/devices/${deviceId}/rdp/${sessionId}`,{cache:"no-store",signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error||"SESSION_LOOKUP_FAILED");if(["closed","failed"].includes(body.status)||Date.parse(body.expiresAt)<=Date.now())setSession(null);else setSession(body)}catch(error){if(!controller.signal.aborted)setMessage(errorMessage(error,"Remote Desktop session status is unavailable."))}},5000);return()=>{controller.abort();clearInterval(timer)}},[deviceId,sessionId,access.canUse]);
 async function start(){setBusy(true);setMessage("");setMissing(false);try{const response=await fetch(`/api/devices/${deviceId}/rdp`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const body=await response.json();if(!response.ok)throw new Error(body.error||"SESSION_CREATE_FAILED");setSession({sessionId:body.sessionId,expiresAt:body.expiresAt,status:"requested"});let opened=false;const markOpened=()=>{opened=true;window.removeEventListener("blur",markOpened);document.removeEventListener("visibilitychange",onVisibility)};const onVisibility=()=>{if(document.visibilityState==="hidden")markOpened()};window.addEventListener("blur",markOpened,{once:true});document.addEventListener("visibilitychange",onVisibility);window.location.href=body.launchUrl;setTimeout(()=>{window.removeEventListener("blur",markOpened);document.removeEventListener("visibilitychange",onVisibility);if(!opened)setMissing(true)},2000)}catch(error){setMessage(errorMessage(error,"Remote Desktop request failed."))}finally{setBusy(false)}}
 async function close(){if(!session)return;setBusy(true);try{const response=await fetch(`/api/devices/${deviceId}/rdp/${session.sessionId}`,{method:"DELETE"});if(!response.ok){const body=await response.json();throw new Error(body.error||"SESSION_CLOSE_FAILED")}setSession(null)}catch(error){setMessage(errorMessage(error,"Remote Desktop session could not be closed."))}finally{setBusy(false)}}
 if(!access.canUse)return <RemoteFeatureGate access={access} feature="Remote Desktop"><button type="button" className="sg-button sg-button-secondary"><ExternalLink size={16}/>Remote Desktop</button></RemoteFeatureGate>;
 return <div className="flex flex-wrap items-center gap-2">{<button type="button" disabled={busy||(!session&&!available)} onClick={()=>void(session?close():start())} className="sg-button sg-button-secondary"><ExternalLink size={16}/>{busy?"Opening...":session?"Close Remote Desktop":"Remote Desktop"}</button>}<a className="sg-button sg-button-ghost sg-button-sm" href={`/api/remote/rdp/download?deviceId=${encodeURIComponent(deviceId)}`} title="Download or repair SentinelGrid Remote"><Wrench size={15} aria-hidden="true" />Install / Repair Remote</a>{message&&<p role="status" className="sr-only">{message}</p>}{missing&&<ViewportDialog label="SentinelGrid Remote required" onDismiss={()=>setMissing(false)}><section role="dialog" aria-modal="true" aria-labelledby="remote-required-title" aria-describedby="remote-required-description" className="w-full max-w-md overflow-hidden rounded-2xl border border-[var(--sg-border)] bg-[var(--sg-surface)] shadow-[0_24px_64px_rgb(0_0_0_/_45%)] animate-in fade-in-0 zoom-in-95 duration-150 motion-reduce:animate-none"><div className="flex items-start justify-between gap-4 border-b border-[var(--sg-border)] px-6 py-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-[color-mix(in_srgb,var(--sg-accent)_30%,var(--sg-border))] bg-[color-mix(in_srgb,var(--sg-accent)_12%,var(--sg-inset))] text-[var(--sg-accent-text)]"><Monitor size={19} aria-hidden="true" /></div><div><p className="text-sm font-semibold text-white">SentinelGrid Remote</p><p className="mt-0.5 text-xs text-[var(--sg-muted)]">Required to start this session</p></div></div><button type="button" onClick={()=>setMissing(false)} className="-mr-2 -mt-2 rounded-lg p-2 text-[var(--sg-muted)] transition hover:bg-[var(--sg-raised)] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--sg-accent)]" aria-label="Close dialog"><X size={17} aria-hidden="true" /></button></div><div className="px-6 py-5"><h2 id="remote-required-title" className="text-base font-semibold text-white">Open this device with SentinelGrid Remote</h2><p id="remote-required-description" className="mt-2 text-sm leading-6 text-zinc-400">Install or repair SentinelGrid Remote, then try the session again.</p></div><div className="flex flex-col-reverse gap-2 border-t border-[var(--sg-border)] bg-[var(--sg-inset)] px-6 py-4 sm:flex-row sm:justify-end"><button type="button" className="sg-button sg-button-secondary" onClick={()=>void(start())}><RotateCcw size={15} aria-hidden="true" />Try Again</button><a className="sg-button sg-button-primary" href={`/api/remote/rdp/download?deviceId=${encodeURIComponent(deviceId)}`}><Download size={15} aria-hidden="true" />Download SentinelGrid Remote</a></div></section></ViewportDialog>}</div>;
}
