import { connection } from "next/server";
import { Activity, Database } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { PageHeader, SectionHeader, Surface } from "@/components/dashboard/dashboard-primitives";
import { StatusBadge } from "@/components/dashboard/dashboard-badges";
const heartbeatWindow = 90_000;
export default async function AdminSystemPage() { await connection(); const admin = createAdminClient(); const [{ error: supabaseError }, { data: agents, error: heartbeatError }, { count: updateActivity, error: updateError }] = await Promise.all([admin.from("organizations").select("id", { head: true }).limit(1), admin.from("devices").select("last_seen").order("last_seen", { ascending: false }).limit(1), admin.from("device_commands").select("*", { count: "exact", head: true }).eq("command_type", "update_agent").gte("created_at", new Date(Date.now() - 86_400_000).toISOString())]); const heartbeat = agents?.[0]?.last_seen; const recentHeartbeat = heartbeat && Date.now() - Date.parse(heartbeat) <= heartbeatWindow;
 const checks = [{ name: "SentinelGrid API", detail: "Serving this administration request", status: "Connected", tone: "success" as const }, { name: "Supabase connectivity", detail: supabaseError ? "Not checked" : "Verified through a server-side query", status: supabaseError ? "Not checked" : "Connected", tone: supabaseError ? "neutral" as const : "success" as const }, { name: "Agent heartbeat activity", detail: heartbeatError ? "Not checked" : recentHeartbeat ? "Recent device heartbeat recorded" : "No recent device heartbeat", status: heartbeatError ? "Not checked" : recentHeartbeat ? "Active" : "No recent activity", tone: heartbeatError ? "neutral" as const : recentHeartbeat ? "success" as const : "warning" as const }, { name: "Update API activity", detail: updateError ? "Not checked" : `${updateActivity ?? 0} update command${updateActivity === 1 ? "" : "s"} recorded in the last 24 hours`, status: updateError ? "Not checked" : "Recorded", tone: updateError ? "neutral" as const : "info" as const }, { name: "Railway relay", detail: "No platform health endpoint is configured", status: "Not checked", tone: "neutral" as const }, { name: "Redis connectivity", detail: "No platform health endpoint is configured", status: "Not checked", tone: "neutral" as const }];
 return <><PageHeader title="System Health" eyebrow="Platform administration" icon={<Activity size={22} />} description="Verified platform signals and observed service activity." /><Surface className="mt-5"><SectionHeader title="Service checks" description="Only completed checks are marked as connected or active." icon={<Database size={17} />} /><div className="divide-y divide-surface-edge">{checks.map((check) => <div key={check.name} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-medium text-zinc-100">{check.name}</p><p className="mt-1 text-xs text-surface-muted">{check.detail}</p></div><StatusBadge status={check.status} tone={check.tone}>{check.status}</StatusBadge></div>)}</div></Surface></>; }
