"use server";

import { revalidatePath } from "next/cache";
import { createAdminClient } from "@/lib/supabase/admin";
import { isPlatformRole, requirePlatformActor, type PlatformRole } from "@/lib/platform-access";

type ActionState = { error?: string; success?: string };
type AuditTarget = { id: string; email?: string | null };
function siteUrl() { return (process.env.NEXT_PUBLIC_SITE_URL ?? "").replace(/\/$/, ""); }
async function auditPlatformAction(actor: { id: string; email: string | null }, action: string, target: AuditTarget, status: "success" | "failed", metadata: Record<string, unknown> = {}) { const admin = createAdminClient(); const { error } = await admin.from("audit_logs").insert({ organization_id: null, user_id: actor.id, actor_email: actor.email, action, target_type: "user", target_id: target.id, target_name: target.email ?? null, status, metadata }); if (error) console.error("[Platform audit] Failed to record action:", error); }
async function targetUser(userId: string) { const admin = createAdminClient(); const { data, error } = await admin.auth.admin.getUserById(userId); if (error || !data.user) throw new Error(error?.message ?? "User not found."); return data.user; }
async function assertTargetIsSafe(actorId: string, userId: string, operation: string) { if (actorId === userId) throw new Error(`You cannot ${operation} your own platform account.`); }
async function assertAnotherPlatformAdministratorRemains(userId: string) { const admin = createAdminClient(); const { data, error } = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 }); if (error) throw new Error("Unable to verify platform administrator coverage."); const others = data.users.filter((user) => user.id !== userId && isPlatformRole(user.app_metadata.platform_role) && !user.banned_until); if (!others.length) throw new Error("This is the last active platform administrator. Assign another administrator before continuing."); }
function result(error: unknown): ActionState { return { error: error instanceof Error ? error.message : "The administrative action could not be completed." }; }

export async function suspendUserAction(userId: string): Promise<ActionState> { let actor: Awaited<ReturnType<typeof requirePlatformActor>> | undefined; let target: Awaited<ReturnType<typeof targetUser>> | undefined; try { actor = await requirePlatformActor(); target = await targetUser(userId); await assertTargetIsSafe(actor.id, userId, "suspend"); if (isPlatformRole(target.app_metadata.platform_role)) await assertAnotherPlatformAdministratorRemains(userId); const { error } = await createAdminClient().auth.admin.updateUserById(userId, { ban_duration: "876000h" }); if (error) throw new Error(error.message); await auditPlatformAction(actor, "platform.user.suspended", target, "success"); revalidatePath("/admin/users"); revalidatePath(`/admin/users/${userId}`); revalidatePath("/admin"); return { success: "Login suspended." }; } catch (error) { if (actor && target) await auditPlatformAction(actor, "platform.user.suspended", target, "failed"); return result(error); } }
export async function restoreUserAction(userId: string): Promise<ActionState> { let actor: Awaited<ReturnType<typeof requirePlatformActor>> | undefined; let target: Awaited<ReturnType<typeof targetUser>> | undefined; try { actor = await requirePlatformActor(); target = await targetUser(userId); const { error } = await createAdminClient().auth.admin.updateUserById(userId, { ban_duration: "none" }); if (error) throw new Error(error.message); await auditPlatformAction(actor, "platform.user.restored", target, "success"); revalidatePath("/admin/users"); revalidatePath(`/admin/users/${userId}`); revalidatePath("/admin"); return { success: "Login restored." }; } catch (error) { if (actor && target) await auditPlatformAction(actor, "platform.user.restored", target, "failed"); return result(error); } }
export async function sendPasswordResetAction(userId: string): Promise<ActionState> { let actor: Awaited<ReturnType<typeof requirePlatformActor>> | undefined; let target: Awaited<ReturnType<typeof targetUser>> | undefined; try { actor = await requirePlatformActor(); target = await targetUser(userId); if (!target.email) throw new Error("This account has no email address for password recovery."); const redirectTo = siteUrl() ? `${siteUrl()}/auth/update-password` : undefined; const { error } = await createAdminClient().auth.resetPasswordForEmail(target.email, redirectTo ? { redirectTo } : undefined); if (error) throw new Error(error.message); await auditPlatformAction(actor, "platform.user.password_reset_requested", target, "success"); return { success: "Password reset email sent." }; } catch (error) { if (actor && target) await auditPlatformAction(actor, "platform.user.password_reset_requested", target, "failed"); return result(error); } }
export async function changePlatformRoleAction(userId: string, role: PlatformRole | null): Promise<ActionState> { let actor: Awaited<ReturnType<typeof requirePlatformActor>> | undefined; let target: Awaited<ReturnType<typeof targetUser>> | undefined; try { actor = await requirePlatformActor(); target = await targetUser(userId); const currentRole = isPlatformRole(target.app_metadata.platform_role) ? target.app_metadata.platform_role : null; if (currentRole && !role) { await assertTargetIsSafe(actor.id, userId, "remove platform access from"); await assertAnotherPlatformAdministratorRemains(userId); }
    const app_metadata = { ...target.app_metadata, platform_role: role };
    const { data, error } = await createAdminClient().auth.admin.updateUserById(userId, { app_metadata });
    if (error) throw new Error(error.message);
    const updatedRole = isPlatformRole(data.user?.app_metadata.platform_role) ? data.user.app_metadata.platform_role : null;
    if (updatedRole !== role) throw new Error(role ? "The platform role could not be applied. Please try again." : "Platform access could not be removed. Please try again.");
    await auditPlatformAction(actor, "platform.user.role_changed", target, "success", { previousRole: currentRole, role }); revalidatePath("/admin/users"); revalidatePath(`/admin/users/${userId}`); return { success: role ? `Platform role set to ${role === "developer" ? "Developer" : "Platform Admin"}.` : "Platform access removed." }; } catch (error) { if (actor && target) await auditPlatformAction(actor, "platform.user.role_changed", target, "failed", { role }); return result(error); } }
export async function deleteUserAction(userId: string): Promise<ActionState> { let actor: Awaited<ReturnType<typeof requirePlatformActor>> | undefined; let target: Awaited<ReturnType<typeof targetUser>> | undefined; try { actor = await requirePlatformActor(); target = await targetUser(userId); await assertTargetIsSafe(actor.id, userId, "delete"); if (isPlatformRole(target.app_metadata.platform_role)) await assertAnotherPlatformAdministratorRemains(userId); const admin = createAdminClient(); const [{ count: ownedCount, error: ownersError }, { count: membershipCount, error: membershipsError }] = await Promise.all([admin.from("organizations").select("id", { count: "exact", head: true }).eq("owner_id", userId), admin.from("organization_members").select("organization_id", { count: "exact", head: true }).eq("user_id", userId)]); if (ownersError || membershipsError) throw new Error("Unable to verify organization relationships before deletion."); if (ownedCount) throw new Error("This user owns one or more organizations. Transfer ownership before deleting this account."); if (membershipCount) throw new Error("Remove this user from all organization memberships before deleting this account."); const { error } = await admin.auth.admin.deleteUser(userId, false); if (error) throw new Error(error.message); await auditPlatformAction(actor, "platform.user.deleted", target, "success"); revalidatePath("/admin/users"); revalidatePath("/admin"); return { success: "User permanently deleted." }; } catch (error) { if (actor && target) await auditPlatformAction(actor, "platform.user.deleted", target, "failed"); return result(error); } }
