import { RadioTower } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { isExpectedUpdateResult } from "@/lib/agent/update-status";
import { PageHeader, SectionHeader, Surface } from "@/components/dashboard/dashboard-primitives";
import { AdminReleaseInventory, type AdminReleaseRow } from "@/components/admin/admin-release-inventory";

type Release = { id: string; version: string; channel: string; is_active: boolean | null; published_at: string | null; architecture: string | null };
type Bundle = { release_id: string; msi_size_bytes: number | null; signer_sha256: string | null; development_build: boolean | null };
type Device = { agent_version: string | null }; type UpdateResult = { error_code: string | null };
export default async function AdminAgentReleasesPage() {
 const admin = createAdminClient(); const [{ data: releases, error }, { data: bundles, error: bundlesError }, { data: devices }, { data: updateResults, error: updatesError }] = await Promise.all([admin.from("agent_releases").select("id, version, channel, is_active, published_at, architecture").order("published_at", { ascending: false }).limit(100).returns<Release[]>(), admin.from("agent_release_bundles").select("release_id, msi_size_bytes, signer_sha256, development_build").returns<Bundle[]>(), admin.from("devices").select("agent_version").returns<Device[]>(), admin.from("device_commands").select("error_code").eq("command_type", "update_agent").eq("status", "failed").limit(1000).returns<UpdateResult[]>()]); const versionCounts = new Map<string, number>(); for (const device of devices ?? []) if (device.agent_version) versionCounts.set(device.agent_version, (versionCounts.get(device.agent_version) ?? 0) + 1); const failures = updateResults ? updateResults.filter((command) => !isExpectedUpdateResult(command.error_code)).length : null;
 const inventory: AdminReleaseRow[] = (releases ?? []).map((release) => { const bundle = bundles?.find((item) => item.release_id === release.id); return { id: release.id, version: release.version, channel: release.channel, active: Boolean(release.is_active), publishedAt: release.published_at, build: `${bundle?.development_build ? "Development" : "Production"}${bundle?.msi_size_bytes ? ` / ${(bundle.msi_size_bytes / 1024 / 1024).toFixed(1)} MB` : ""}`, signer: bundle?.signer_sha256 ? `${bundle.signer_sha256.slice(0, 12)}...` : "Not available", devices: versionCounts.get(release.version) ?? 0 }; });
 return <><PageHeader title="Agent Releases" eyebrow="Platform administration" icon={<RadioTower size={22} />} description="Published Agent release inventory and fleet adoption." /><Surface className="mt-5 overflow-hidden"><SectionHeader title="Releases" description={updatesError ? "Update failure records could not be loaded." : `${failures ?? 0} recorded update failure${failures === 1 ? "" : "s"}. Search and filters update instantly.`} icon={<RadioTower size={17} />} />{error || bundlesError ? <div role="alert" className="sg-inline-notice">Release inventory could not be loaded: {(error ?? bundlesError)?.message ?? "Unknown database error"}</div> : <AdminReleaseInventory releases={inventory} />}</Surface></>;
}
