"use client";

import { useDeferredValue, useMemo, useState } from "react";
import { StatusBadge } from "@/components/dashboard/dashboard-badges";
import { AdminFilterBar, FilterSelect } from "@/components/admin/admin-inventories";

export type AdminReleaseRow = { id: string; version: string; channel: string; active: boolean; publishedAt: string | null; build: string; signer: string; devices: number };
export function AdminReleaseInventory({ releases }: { releases: AdminReleaseRow[] }) {
  const [query, setQuery] = useState(""); const [channel, setChannel] = useState(""); const [active, setActive] = useState(""); const deferredQuery = useDeferredValue(query.toLowerCase().trim());
  const shown = useMemo(() => releases.filter((release) => (!deferredQuery || release.version.toLowerCase().includes(deferredQuery)) && (!channel || release.channel === channel) && (!active || String(release.active) === active)), [active, channel, deferredQuery, releases]);
  const filtered = Boolean(query || channel || active);
  return <><AdminFilterBar query={query} setQuery={setQuery} placeholder="Search version"><FilterSelect value={channel} onChange={setChannel} label="Release channel" options={[["", "All channels"], ["stable", "Stable"], ["beta", "Beta"]]} /><FilterSelect value={active} onChange={setActive} label="Release status" options={[["", "All statuses"], ["true", "Active"], ["false", "Inactive"]]} />{filtered && <button type="button" className="sg-admin-filter-reset" onClick={() => { setQuery(""); setChannel(""); setActive(""); }}>Reset filters</button>}</AdminFilterBar><div className="divide-y divide-surface-edge"><div className="sg-table-heading hidden grid-cols-[0.7fr_0.55fr_0.5fr_0.7fr_0.6fr_0.6fr_0.5fr] gap-4 px-5 py-3 lg:grid"><span>Version</span><span>Channel</span><span>Active</span><span>Published</span><span>Build</span><span>Signer</span><span>Devices</span></div>{shown.map((release) => <div key={release.id} className="sg-admin-interactive-row grid gap-3 px-5 py-4 lg:grid-cols-[0.7fr_0.55fr_0.5fr_0.7fr_0.6fr_0.6fr_0.5fr] lg:items-center"><Field label="Version" value={`v${release.version}`} mono /><Field label="Channel" value={release.channel} /><Field label="Active" value={<StatusBadge status={release.active ? "Active" : "Inactive"} tone={release.active ? "success" : "neutral"}>{release.active ? "Active" : "Inactive"}</StatusBadge>} /><Field label="Published" value={release.publishedAt ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(release.publishedAt)) : "Not available"} /><Field label="Build" value={release.build} /><Field label="Signer" value={release.signer} mono /><Field label="Devices" value={release.devices} /></div>)}{!shown.length && <p className="px-5 py-8 text-sm text-surface-muted">No releases match the current filters.</p>}</div></>;
}
function Field({ label, value, mono = false }: { label: string; value: React.ReactNode; mono?: boolean }) { return <div className={`flex justify-between gap-3 text-xs text-zinc-300 lg:block ${mono ? "font-mono" : ""}`}><span className="sg-meta lg:hidden">{label}</span><span>{value}</span></div>; }
